-- 医疗陪诊服务平台 - 数据库初始化脚本
-- 使用前请先创建数据库: CREATE DATABASE pz_medical CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS pz_medical CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE pz_medical;

-- H5用户表
CREATE TABLE IF NOT EXISTS h5_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    name VARCHAR(50) COMMENT '昵称',
    avatar VARCHAR(500) COMMENT '头像',
    mobile VARCHAR(20) COMMENT '手机号',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='H5用户';

-- 管理员表
CREATE TABLE IF NOT EXISTS admin_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名/手机号',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    name VARCHAR(50) COMMENT '昵称',
    mobile VARCHAR(20) COMMENT '手机号',
    permissions_id INT DEFAULT 0 COMMENT '权限组ID',
    active TINYINT DEFAULT 1 COMMENT '状态 1正常 0失效',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员';

-- 菜单表
CREATE TABLE IF NOT EXISTS menu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '菜单名称',
    parent_id INT DEFAULT 0 COMMENT '父级ID',
    icon VARCHAR(50) COMMENT '图标',
    path VARCHAR(200) COMMENT '前端路由path',
    component VARCHAR(200) COMMENT '组件路径',
    `describe` TEXT COMMENT '描述',
    sort INT DEFAULT 0 COMMENT '排序',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单';

-- 菜单角色表
CREATE TABLE IF NOT EXISTS menu_role (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '角色名称',
    permissions JSON COMMENT '权限菜单ID列表',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单角色';

-- 医院表
CREATE TABLE IF NOT EXISTS hospital (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT '医院名称',
    rank VARCHAR(50) COMMENT '等级',
    label VARCHAR(100) COMMENT '标签',
    intro TEXT COMMENT '简介',
    avatar_url VARCHAR(500) COMMENT '图片URL',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医院';

-- 陪诊师表
CREATE TABLE IF NOT EXISTS companion (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL COMMENT '名称',
    avatar VARCHAR(500) COMMENT '头像',
    sex TINYINT DEFAULT 1 COMMENT '性别 1男 2女',
    age INT DEFAULT 20 COMMENT '年龄',
    mobile VARCHAR(20) COMMENT '手机号',
    active TINYINT DEFAULT 1 COMMENT '状态 1正常 0失效',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='陪诊师';

-- 服务项目表
CREATE TABLE IF NOT EXISTS service (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT '服务名称',
    service_img VARCHAR(500) COMMENT '服务图片',
    price DECIMAL(10,2) DEFAULT 0 COMMENT '价格',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务项目';

-- 订单表
CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    out_trade_no VARCHAR(50) NOT NULL UNIQUE COMMENT '订单号',
    user_id INT COMMENT '用户ID',
    hospital_id INT COMMENT '医院ID',
    hospital_name VARCHAR(100) COMMENT '医院名称',
    service_id INT COMMENT '服务ID',
    service_name VARCHAR(100) COMMENT '服务名称',
    service_img VARCHAR(500) COMMENT '服务图片',
    companion_id INT COMMENT '陪诊师ID',
    companion_name VARCHAR(50) COMMENT '陪诊师名称',
    client_name VARCHAR(50) COMMENT '就诊人',
    client_mobile VARCHAR(20) COMMENT '就诊人电话',
    starttime BIGINT COMMENT '期望就诊时间戳',
    receive_address VARCHAR(500) COMMENT '接送地址',
    tel VARCHAR(20) COMMENT '联系电话',
    demand TEXT COMMENT '其他需求',
    trade_state VARCHAR(20) DEFAULT '待支付' COMMENT '订单状态',
    price DECIMAL(10,2) DEFAULT 0 COMMENT '总价',
    paid_price DECIMAL(10,2) DEFAULT 0 COMMENT '已付',
    order_start_time BIGINT COMMENT '下单时间戳',
    code_url VARCHAR(500) COMMENT '支付二维码链接',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单';

-- 轮播图表
CREATE TABLE IF NOT EXISTS slides (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pic_image_url VARCHAR(500) COMMENT '图片URL',
    sort INT DEFAULT 0 COMMENT '排序',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='轮播图';

-- 图片库表
CREATE TABLE IF NOT EXISTS photo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(500) COMMENT '图片URL',
    name VARCHAR(100) COMMENT '图片名称',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图片库';
